#!/usr/bin/env bash
# Deploys the full stack from an empty resource group.
#
# Usage:
#   ./deploy.sh <resource-group-name> [location]
#
# Requires: az CLI logged in (`az login`) with a subscription selected
# (`az account set --subscription <id>`).
set -euo pipefail

RESOURCE_GROUP="${1:?Usage: deploy.sh <resource-group-name> [location]}"
LOCATION="${2:-swedencentral}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"

echo "==> Ensuring resource group '$RESOURCE_GROUP' exists in $LOCATION"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none

echo "==> Validating template"
az deployment group validate \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$INFRA_DIR/main.bicep" \
  --parameters "$INFRA_DIR/main.bicepparam" \
  --output none

echo "==> Deploying (this can take 5-10 minutes on first run: AI Search + OpenAI model deployments are slow)"
az deployment group create \
  --name "deploy-$(date +%Y%m%d%H%M%S)" \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$INFRA_DIR/main.bicep" \
  --parameters "$INFRA_DIR/main.bicepparam" \
  --output json > /tmp/deploy-output.json

echo "==> Deployment complete. Resource outputs:"
az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "$(jq -r '.name' /tmp/deploy-output.json)" \
  --query properties.outputs \
  --output json

echo ""
echo "==> Writing team hand-off env file to $INFRA_DIR/scripts/.generated.env (NOT committed - see .gitignore)"
OUTPUTS=$(az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "$(jq -r '.name' /tmp/deploy-output.json)" \
  --query properties.outputs \
  --output json)

cat > "$INFRA_DIR/scripts/.generated.env" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
AZURE_STORAGE_ACCOUNT_NAME=$(echo "$OUTPUTS" | jq -r '.storageAccountName.value')
BLOB_CONTAINER_NAME=$(echo "$OUTPUTS" | jq -r '.blobContainerName.value')
STORAGE_QUEUE_NAME=$(echo "$OUTPUTS" | jq -r '.queueName.value')
JOB_STATUS_TABLE_NAME=$(echo "$OUTPUTS" | jq -r '.jobStatusTableName.value')
AZURE_SEARCH_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.searchEndpoint.value')
AZURE_OPENAI_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.openAiEndpoint.value')
OPENAI_CHAT_DEPLOYMENT=$(echo "$OUTPUTS" | jq -r '.chatDeploymentName.value')
OPENAI_EMBEDDING_DEPLOYMENT=$(echo "$OUTPUTS" | jq -r '.embeddingDeploymentName.value')
BACKEND_URL=https://$(echo "$OUTPUTS" | jq -r '.backendFqdn.value')
STATIC_WEB_APP_HOSTNAME=$(echo "$OUTPUTS" | jq -r '.staticWebAppDefaultHostname.value')
EOF

echo "==> Done. Share $INFRA_DIR/scripts/.generated.env with the team (out of band, it is gitignored)."
echo ""
echo "==> Next steps this script does NOT do for you:"
echo "    1. Register an Entra ID App (see register-entra-app.sh), then re-run this"
echo "       script after setting entraTenantId/entraApiClientId in main.bicepparam"
echo "       so the backend gets real auth config."
echo "    2. Build and push a real backend image, then update the Container App revision"
echo "       (the CI workflow in .github/workflows/ci-backend.yml does this on push to main)."
echo "    3. Fetch the Static Web App deployment token for CI:"
echo "       az staticwebapp secrets list --name $(echo "$OUTPUTS" | jq -r '.staticWebAppName.value') --query properties.apiKey -o tsv"
