#!/usr/bin/env bash
# Deploys the full stack from an empty resource group.
#
# Usage:
#   ./deploy.sh <resource-group-name> [location]
#
# Requires: az CLI logged in (`az login`) with a subscription selected
# (`az account set --subscription <id>`).
set -euo pipefail

RESOURCE_GROUP="${1:?Usage: deploy.sh <resource-group-name> [location]}"
LOCATION="${2:-swedencentral}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"

echo "==> Ensuring resource group '$RESOURCE_GROUP' exists in $LOCATION"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none

echo "==> Validating template"
az deployment group validate \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$INFRA_DIR/main.bicep" \
  --parameters "$INFRA_DIR/main.bicepparam" \
  --output none

DEPLOYMENT_NAME="deploy-$(date +%Y%m%d%H%M%S)"

echo "==> Deploying as '$DEPLOYMENT_NAME' (this can take 5-10 minutes on first run: AI Search + OpenAI model deployments are slow)"
az deployment group create \
  --name "$DEPLOYMENT_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$INFRA_DIR/main.bicep" \
  --parameters "$INFRA_DIR/main.bicepparam" \
  --output none

echo "==> Deployment complete. Resource outputs:"
az deployment group show \
  --resource-group "$RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --query properties.outputs \
  --output json

# Small helper: fetch one output value by name as plain text.
out() {
  az deployment group show \
    --resource-group "$RESOURCE_GROUP" \
    --name "$DEPLOYMENT_NAME" \
    --query "properties.outputs.$1.value" \
    --output tsv
}

echo ""
echo "==> Writing team hand-off env file to $INFRA_DIR/scripts/.generated.env (NOT committed - see .gitignore)"

cat > "$INFRA_DIR/scripts/.generated.env" <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
AZURE_STORAGE_ACCOUNT_NAME=$(out storageAccountName)
BLOB_CONTAINER_NAME=$(out blobContainerName)
STORAGE_QUEUE_NAME=$(out queueName)
JOB_STATUS_TABLE_NAME=$(out jobStatusTableName)
AZURE_SEARCH_ENDPOINT=$(out searchEndpoint)
AZURE_OPENAI_ENDPOINT=$(out openAiEndpoint)
OPENAI_CHAT_DEPLOYMENT=$(out chatDeploymentName)
OPENAI_EMBEDDING_DEPLOYMENT=$(out embeddingDeploymentName)
BACKEND_URL=https://$(out backendFqdn)
STATIC_WEB_APP_HOSTNAME=$(out staticWebAppDefaultHostname)
EOF

echo "==> Done. Share $INFRA_DIR/scripts/.generated.env with the team (out of band, it is gitignored)."
echo ""
echo "==> Next steps this script does NOT do for you:"
echo "    1. Register an Entra ID App (see register-entra-app.sh), then re-run this"
echo "       script after setting entraTenantId/entraApiClientId in main.bicepparam"
echo "       so the backend gets real auth config."
echo "    2. Build and push a real backend image, then update the Container App revision"
echo "       (the CI workflow in .github/workflows/ci-backend.yml does this on push to main)."
echo "    3. Fetch the Static Web App deployment token for CI:"
echo "       az staticwebapp secrets list --name $(out staticWebAppName) --query properties.apiKey -o tsv"
